stale: Adding a function to integrate axes
I am facing the error: "AttributeError: 'ConstructProxy' object has no attribute 'fill'"

FAILED tests/test_general.py::test_integrate - AttributeError: 'ConstructProxy' object has no attribute 'fill'.

I think I am missing small hint to run the code successful. And I am wondering if I put the function in right location of basehist or which right way to fix the issue I am facing.